apiVersion: kustomization.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: dev
